# Generated by Django 5.2.6 on 2025-10-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldr',
            name='collaborators',
            field=models.ManyToManyField(to='users.user'),
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AddField(
            model_name='ldr',
            name='songs',
            field=models.ManyToManyField(to='content.song'),
        ),
    ]
