# Generated by Django 5.2.7 on 2025-11-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('notificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interaccion.notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('notificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interaccion.notificacion')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitado', to='usuarios.usuario')),
            ],
        ),
    ]
