# Generated by Django 5.2.6 on 2025-10-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('message', models.TextField(db_default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interaction.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('notificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interaction.notification')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to='users.user')),
            ],
        ),
    ]
