# Generated by Django 5.2.7 on 2025-11-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('publicacion', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.artista')),
            ],
        ),
        migrations.CreateModel(
            name='LDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('canciones', models.ManyToManyField(to='contenido.cancion')),
                ('editores', models.ManyToManyField(to='usuarios.usuario')),
            ],
        ),
    ]
