# Generated by Django 5.2.7 on 2025-11-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
